### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by skaliush** [Hanqnero/itmolab3#2]
- Зачем везде пустые конструкторы?
- По красоте сначала должны быть перечислены свойства класса, а затем его методы
- Там где перед добавлением объекта в список, ты проверяешь нет ли ещё этого объекта в списке, по логике вещей нужно использовать set, а не list. Примеры: dislikedItems, currentClothes.
- LifeStatus - зачем енам, если можно сделать просто boolean. То же и у енама State у класса Coffin.
- Лучше использовать ArrayList вместо LinkedList: в 90% случаев ArrayList быстрее и экономичнее LinkedList
- Некоторые методы повторяются у многих людей, например addClothingItem или consumeFood. Почему бы их не вынести в класс Person? Во-первых это дублирование кода, во-вторых разве вообще предполагается разная реализация этих методов?

**Comment by Hanqnero** [comment]
Исправлено в https://github.com/Hanqnero/itmolab3/pull/3
